config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions' }
  root to:'toppage#index'
  
  resources :users, only: [:show, :index] do
    collection do
      get 'sell', to: 'users#sell'
      get 'sold', to: 'users#sold'
    end
  end

  
  resources :cards, only: [:new, :show, :index, :edit] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
      post 'buy/:id', to: 'cards#buy'
    end
  end
  resources :toppage, only: :index

  resources :images, only: [:destroy]

  resources :products do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :categories, only: [:show, :index]
  
  resources :addresses, only: [:new, :create, :edit, :update] do
    collection do
      get 'mypage_new', to: 'addresses#mypage_new'
      post 'mypage_create', to: 'addresses#mypage_create'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, uniqueness: true
  validates :family_name, presence: true,format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: 'は日本語で入力して下さい。'}
  validates :first_name, presence: true,format: { with: /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/, message: 'は日本語で入力して下さい。'}
  validates :kana_family_name, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :kana_first_name, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :birthday, presence: true
  validates :telnumber, presence: true

  has_many :cards
  has_many :products
  has_many :addresses
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
    new_address_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_product, only: [:show, :sell, :sold]
    def index
    end

    def show
        @user = User.find(params[:id])
        @sell = @product.where(status: 1)
        @sold = @product.where(status: 2)
    end

    def sell
        @goods = @product.where(status: 1)
    end

    def sold
        @goods = @product.where(status: 2)
    end
    private
    def set_product
        @product = current_user.products
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_goods.html.haml
= render 'toppage/header'

.main
  .main__box
    = render 'left-memu'

    .my-main-goods
      .my-main-goods__box
        - @goods.each do |goods|
          .main__pick__box__lists__list
            = link_to product_path(goods.id), class:"main__pick__box__lists__list__a" do
              .product-image
                - if goods.status != "2"
                - else
                  .sold-date
                    %p
                - if goods.images.blank?
                - else
                  = image_tag "#{goods.images[0].image}", class: "product-image__i1"
              .main__pick__box__lists__list__a__text
                .main__pick__box__lists__list__a__text__name
                  = goods.name
                .main__pick__box__lists__list__a__text__box
                  .main__pick__box__lists__list__a__text__box__price
                    = goods.price
                  .main__pick__box__lists__list__a__text__box__tax
                    (税込)   




= render 'toppage/footer'

app/views/users/_left-memu.html.haml
.my-side
  %nav.my-side__nav{role: "navigation"}
    %ul.my-side__nav__lists
      %li.my-side__nav__lists__list
        = link_to 'マイページ', user_path(current_user), class:"my-side__nav__lists__list__name", data: {"turbolinks" => false}
      %li.my-side__nav__lists__list
        = link_to '出品した商品-出品中', sell_users_path, class: "my-side__nav__lists__list__name"
      %li.my-side__nav__lists__list
        = link_to '出品した商品-売却済', sold_users_path, class: "my-side__nav__lists__list__name"

    %h3.my-side__nav__title
      設定
    %ul.my-side__nav__lists
      %li.my-side__nav__lists__list
        = link_to '発送元・お届け先住所変更', edit_address_path(current_user), class: "my-side__nav__lists__list__name"
      %li.my-side__nav__lists__list
        = link_to '支払い方法', new_card_path, data: {"turbolinks" => false}, class: "my-side__nav__lists__list__name"
      %li.my-side__nav__lists__list
        = link_to 'メール/パスワード', edit_user_registration_path(current_user), class: "my-side__nav__lists__list__name"
      %li.my-side__nav__lists__list
        %a.my-side__nav__lists__list__name{href: "/users"} ログアウト

app/views/users/index.html.haml
= render 'toppage/header'

.main
  .main__box
    = render 'left-memu'

    .my-main
      .logout
        .logout__box
          = link_to destroy_user_session_path, method: :delete, class:".logout__box__bm" do 
            %p.logout__box__bm__btn ログアウト

= render 'toppage/footer'

app/views/users/sell.html.haml
= render 'goods'

app/views/users/show.html.haml
= render 'toppage/header'

.main
  .main__box
    = render 'left-memu'

    .my-main
      .my-main__top
        = image_tag('mypage-img.png', class:"my-back")
        .my-main__top__box
          .my-main__top__box__image
            = image_tag('icon/member_photo_noimage_thumb.png', class:"my-icon")
            %h2.nickname 
              = @user.nickname
            .my-main__top__box__image__date
              %p.goodsnum 出品数
              %span.goodssum 
                = @product.length
      .my-main__goods
        %h2.title 売買した商品
        %ul.buys
          %li{class:"buys__status active", id:"now"}
            %span(href='#') 出品中
          %li{class: "buys__status", id:"ago"}
            %span(href='#') 売却済み
        .my-main__goods__box
          %ul.buy-goods
            - if @sell.present?
              %li{class: 'buy-goods__status show'}
                - @sell.each do |sell|
                  = link_to product_path(sell.id) do
                    .minigoods
                      .imagmini
                        - if sell.images.blank?
                        - else
                          = image_tag "#{sell.images[0].image}", class: "product-imagemini"
                      .textmini
                        %p.mygoods #{sell.name}
                        %p.mygoods #{sell.price}円
            - else
              %li{class: 'buy-goods__status show'} 出品中の商品はありません
            - if @sold.present?
              %li{class: 'buy-goods__status'} 
                - @sold.each do |sold|
                  = link_to product_path(sold.id) do
                    .minigoods
                      .imagmini
                        - if sold.images.blank?
                        - else
                          = image_tag "#{sold.images[0].image}", class: "product-imagemini"
                      .textmini
                        %p.mygoods #{sold.name}
                        %p.mygoods #{sold.price}円
            - else
              %li{class: 'buy-goods__status'} 売却した商品はありません

= render 'toppage/footer'

app/views/users/sold.html.haml
= render 'goods'