config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions' }
  root to:'toppage#index'
  
  resources :users, only: [:show, :index] do
    collection do
      get 'sell', to: 'users#sell'
      get 'sold', to: 'users#sold'
    end
  end

  
  resources :cards, only: [:new, :show, :index, :edit] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
      post 'buy/:id', to: 'cards#buy'
    end
  end
  resources :toppage, only: :index

  resources :images, only: [:destroy]

  resources :products do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :categories, only: [:show, :index]
  
  resources :addresses, only: [:new, :create, :edit, :update] do
    collection do
      get 'mypage_new', to: 'addresses#mypage_new'
      post 'mypage_create', to: 'addresses#mypage_create'
    end
  end

end

app/controllers/toppage_controller.rb
class ToppageController < ApplicationController
  def index
    @goods = Product.all.order(created_at: :desc).limit(3)
  end

end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/views/toppage/_exhibit.html.haml
- if user_signed_in?
  = link_to new_product_path, class:"exhibit", data: {"turbolinks" => false} do
    .exhibit__box
      .exhibit__box__text
        出品する
      = image_tag("icon/icon_camera.png", class: ".exhibit__box__image", width: "50px")

app/views/toppage/_footer.html.haml
.footer
  .footer__content
    .footer__content__list
      .footer__content__list__title
        FURIMAについて
      .footer__content__list__text
        .footer__content__list__text__box1
          %p.footer__content__list__text__box1__a
            会社概要（運営会社）
        .footer__content__list__text__box1
          %p.footer__content__list__text__box1__a
            プライバシーポリシー
        .footer__content__list__text__box1
          %p.footer__content__list__text__box1__a
            FURIMA利用規約
        .footer__content__list__text__box1
          %p.footer__content__list__text__box1__a
            ポイントに関する特約

    .footer__content__list
      .footer__content__list__title
        FURIMAを見る
      .footer__content__list__text
        .footer__content__list__text__box1
          = link_to "/categories", class: "footer__content__list__text__box1__a" do
            カテゴリー一覧

    .footer__content__list
      .footer__content__list__title
        ヘルプ&ガイド
      .footer__content__list__text
        .footer__content__list__text__box1
          %p.footer__content__list__text__box1__a
            FURIMAガイド
        .footer__content__list__text__box1
          %p.footer__content__list__text__box1__a
            FURIMAロゴ利用ガイドライン
        .footer__content__list__text__box1
          %p.footer__content__list__text__box1__a
            お知らせ

  .footer__logo
    = link_to image_tag('logo/logo-white.png', width:'150px', class: "footer__logo__image"), root_path
  .footer__bottom
    ©FURIMA

app/views/toppage/_goods.html.haml
= render 'toppage/header'

.main
  .main__box
    = render 'users/left-memu'
    .my-main-goods
      .my-main-goods__box
        - @goods.each do |goods|
          .main__pick__box__lists__list
            = link_to product_path(goods.id), class:"main__pick__box__lists__list__a" do
              .product-image
                - if goods.status != "2"
                - else
                  .sold-date
                    %p
                = image_tag "#{goods.images[0].image}", class: "product-image__i1"
              .main__pick__box__lists__list__a__text
                .main__pick__box__lists__list__a__text__name
                  = goods.name
                .main__pick__box__lists__list__a__text__box
                  .main__pick__box__lists__list__a__text__box__price
                    = goods.price
                  .main__pick__box__lists__list__a__text__box__tax
                    (税込)   




= render 'toppage/footer'

app/views/toppage/_header.html.haml
.header
  .header__inner
    .header__inner__main
      .header__inner__main__icon
        = link_to image_tag('logo/logo.png', width:'150px'), root_path
      .header__inner__main__seach
        = form_with(url:"#",local: true, method: :get, class: "header__inner__main__seach__form") do |form|
          = form.text_field :keyword, placeholder: "検索機能は実装しておりません", class: "header__inner__main__seach__form__input"
          = form.submit "", class: "header__inner__main__seach__form__btn"
    .header__inner__nav
      .header__inner__nav__left
        .header__inner__nav__left__ca
          = link_to "/categories" do
            カテゴリー
          %ul.header__inner__nav__left__ca__parents
            = render partial:'categories/ca-header', collection: @parents.roots, as: "parent"
            = link_to "カテゴリー一覧から探す", "/categories", class:"allcate"
            
            

      .header__inner__nav__right
        .header__inner__nav__right__log
          - if user_signed_in?
          - else
            = link_to "/users/sign_in" do
              ログイン
        .header__inner__nav__right__sign
          - if user_signed_in?
          - else
            = link_to "/users/sign_up" do
              新規会員登録
        .header__inner__nav__right__sign
          - if user_signed_in?
            = link_to "マイページ", user_path(current_user), data: {"turbolinks" => false}
          - else
            = link_to "/users/sign_in" do
              マイページ

app/views/toppage/_main.html.haml
.main
  .main__devise
    %p.flash 
      = flash[:now]
  .main__image1
    .main__image1__content
      .main__image1__content__title
        人生を変えるフリマアプリ
      .main__image1__content__text
        FURIMAはだれでもかんたんに出品・購入できるフリマアプリです
      .main__image1__content__btn
        = image_tag('http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', width:'180px')
        = image_tag('http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg', width:'180px')





  .main__ponta
    .main__ponta__title
      FURIMAが選ばれるが選ばれる３つの理由
      .main__ponta__title__line

    .main__ponta__th
      .main__ponta__th__box1
        .main__ponta__th__box1__image
          .main__ponta__th__box1__image__num
            1
          .main__ponta__th__box1__image__a
            = image_tag("/images/pict-reason-01.jpg", width: '300px')
        .main__ponta__th__box1__title
          .main__ponta__th__box1__title__num2
            3分
          .main__ponta__th__box1__title__text
            ですぐに出品
        .main__ponta__th__box1__bottom
          スマホで入力するだけで簡単に出品できる！

      .main__ponta__th__box1
        .main__ponta__th__box1__image
          .main__ponta__th__box1__image__num
            2
          .main__ponta__th__box1__image__a
            = image_tag("/images/pict-reason-02.jpg", width: '300px')
        .main__ponta__th__box1__title
          .main__ponta__th__box1__title__num2
            シンプル
          .main__ponta__th__box1__title__text
            で使いやすい
        .main__ponta__th__box1__bottom
          めんどくさい入力は必要なく、検索も購入もスムーズ！

      .main__ponta__th__box1
        .main__ponta__th__box1__image
          .main__ponta__th__box1__image__num
            3
          .main__ponta__th__box1__image__a
            = image_tag("/images/pict-reason-03.jpg", width: '300px')
        .main__ponta__th__box1__title
          .main__ponta__th__box1__title__text
            手数料
          .main__ponta__th__box1__title__num2
            業界最安
        .main__ponta__th__box1__bottom
          めんどくさい入力は必要なく、検索も購入もスムーズ！


  .main__image2
    .main__image2__content
      .main__image2__content__title
        会員数日本一位
      .main__image2__content__text
        FURIMAは、フリマアプリで最も人気。
      .main__image2__content__text
        出品・購入回数も業界最多です！
      .main__image2__content__text
        ほしかったあの商品に出会えるかもしれません。
      .main__image2__content__btn
        = image_tag('http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', width:'180px')
        = image_tag('http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg', width:'180px')



  .main__feature
    .main__ponta__title
      FURIMAの特徴
      .main__ponta__title__line
    
    .main__feature__box
      .main__feature__box__m1
        .main__feature__box__m1__image
          = image_tag("icon/icon-01.png", width: '210px')
        .main__feature__box__m1__text-top
          簡単に売り買いできる
        .main__feature__box__m1__text-bottom
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！

      .main__feature__box__m1
        .main__feature__box__m1__image
          = image_tag("icon/icon-03.png", width: '210px')
        .main__feature__box__m1__text-top
          売上金は即日振込みに対応
        .main__feature__box__m1__text-bottom
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!

      .main__feature__box__m1
        .main__feature__box__m1__image
          = image_tag("icon/icon-04.png", width: '210px')
        .main__feature__box__m1__text-top
          様々な支払いに対応
        .main__feature__box__m1__text-bottom
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  .main__pick
    .main__pick__title
      ピックアップカテゴリー
    .main__pick__box
      .main__pick__box__new
        %p.subtitle 新規投稿商品
      .main__pick__box__lists
        - @goods.each do |item|
          .main__pick__box__lists__list
            = link_to product_path(item), class:"main__pick__box__lists__list__a" do
              .product-image
                - if item.status != "2"
                - else
                  .sold-date
                    %p
                - if item.images.blank?
                - else
                  = image_tag "#{item.images[0].image}", class: "product-image__i1"
              .main__pick__box__lists__list__a__text
                .main__pick__box__lists__list__a__text__name
                  = item.name
                .main__pick__box__lists__list__a__text__box
                  .main__pick__box__lists__list__a__text__box__price
                    = item.price
                  .main__pick__box__lists__list__a__text__box__tax
                    (税込)



  .main__pick
    .main__pick__title
      ピックアップブランド
    .main__pick__box
      .main__pick__box__new
        %p.subtitle アーカイバ
      .main__pick__box__lists
        .main__pick__box__lists__list
          .main__pick__box__lists__list__a
            .product-image
              = image_tag("https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/13/a007.png", class: "product-image__i1")
            .main__pick__box__lists__list__a__text
              .main__pick__box__lists__list__a__text__name
                魚
              .main__pick__box__lists__list__a__text__box
                .main__pick__box__lists__list__a__text__box__price
                  30000円
                  .main__pick__box__lists__list__a__text__box__price__box1
                .main__pick__box__lists__list__a__text__box__tax
                  (税込)

        .main__pick__box__lists__list
          .main__pick__box__lists__list__a
            .product-image
              = image_tag("https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "product-image__i1")
            .main__pick__box__lists__list__a__text
              .main__pick__box__lists__list__a__text__name
                料理
              .main__pick__box__lists__list__a__text__box
                .main__pick__box__lists__list__a__text__box__price
                  30000円
                  .main__pick__box__lists__list__a__text__box__price__box1
                .main__pick__box__lists__list__a__text__box__tax
                  (税込)

        .main__pick__box__lists__list
          .main__pick__box__lists__list__a
            .product-image
              = image_tag("https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/7/a001.png", class: "product__image__i1")
            .main__pick__box__lists__list__a__text
              .main__pick__box__lists__list__a__text__name
                カレー
              .main__pick__box__lists__list__a__text__box
                .main__pick__box__lists__list__a__text__box__price
                  30000円
                  .main__pick__box__lists__list__a__text__box__price__box1
                .main__pick__box__lists__list__a__text__box__tax
                  (税込)
                

  .main__image3
    .main__image3__content
      .main__image3__content__title
        だれでもかんたん、人生を変えるフリマアプリ
      .main__image3__content__text
        今すぐ無料ダウンロード！
      .main__image3__content__btn
        = image_tag('http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg', width:'180px')
        = image_tag('http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg', width:'180px')

app/views/toppage/index.html.haml
.wrapper
  = render "header"
  = render "main"
  = render "footer"
  = render "exhibit"