config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions' }
  root to:'toppage#index'
  
  resources :users, only: [:show, :index] do
    collection do
      get 'sell', to: 'users#sell'
      get 'sold', to: 'users#sold'
    end
  end

  
  resources :cards, only: [:new, :show, :index, :edit] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
      post 'buy/:id', to: 'cards#buy'
    end
  end
  resources :toppage, only: :index

  resources :images, only: [:destroy]

  resources :products do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :categories, only: [:show, :index]
  
  resources :addresses, only: [:new, :create, :edit, :update] do
    collection do
      get 'mypage_new', to: 'addresses#mypage_new'
      post 'mypage_create', to: 'addresses#mypage_create'
    end
  end

end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :user
    
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:edit, :buy]
  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "index" if card.exists?
  end

  def pay 
    Payjp.api_key = ENV["KEY"]
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) 
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "index"
      else
        redirect_to action: "new"
      end
  end

  def delete 
    card = Card.where(user_id: current_user.id).first
      Payjp.api_key = ENV["KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      if card.delete
        redirect_to action: "new", notice: "削除しました"
      else 
        redirect_to action: "index", alert: "削除できませんでした"
      end

  end

  def index
    card = Card.find_by(user_id: current_user.id)
      Payjp.api_key = ENV["KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
      
      @card_brand = @default_card_information.brand      
      case @card_brand
      when "Visa"
        @card_src = "visa.png"
      when "JCB"
        @card_src = "jcb.gif"
      when "MasterCard"
        @card_src = "mastercard.png"
      when "American Express"
        @card_src = "american-express.png"
      when "Discover"
        @card_src = "discover.png"
      end

    end

    def edit
      Payjp.api_key = ENV["KEY"]
      card = Card.where(user_id: current_user.id).first
      @address = Address.find_by(user_id: current_user.id)
      if current_user.id == @product.id
        redirect_to root_path
      elsif @product.status == "2"
        redirect_to root_path
      end
      if card.present?
        customer = Payjp::Customer.retrieve(card.customer_id)
        @default_card_information = customer.cards.retrieve(card.card_id)
      end
    end
  
    def buy
      Payjp.api_key = ENV['KEY']
      card = Card.where(user_id: current_user.id).first
      if current_user.id != @product.id && @product.status == "1"
        Payjp::Charge.create(
        amount: @product.price,
        customer: card.customer_id, 
        currency: 'jpy'
      )
      end
    if @product.update(status: 2)
      redirect_to action: 'show'
    else
      redirect_to action: 'edit', notice: "購入できませんでした"
    end
    end

    private

    def set_product
      @product = Product.find(params[:id])
    end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.haml
#account-page.account-page
  .account-page__inner1.clearfix
    .page__header
      %h1
        = link_to image_tag("logo/logo.png", class:"header__logo"), root_path
    .page__main
      %h2.title 購入内容の確認
    .page__main__forms
      .page__main__forms__date
        .page__main__forms__date__image
          = image_tag "#{@product.images[0].image}", class:"buyimg"
        .page__main__forms__date__text
          %p 
            = @product.name
          %p.price
            ￥#{@product.price}

      .page__main__forms__money
        %p.money 支払い金額
        %h3.money
          ￥#{@product.price}
      .page__main__forms__buy
        %h3.buytitle 支払い方法
        - if @default_card_information.blank?
          .page__main__forms__buy__nodate
            %p 購入にはクレジットカードの登録が必要です。
            %br
              = link_to 'こちら', new_card_path, class:"here", data: {"turbolinks" => false}
              から登録する。
        - else
          .page__main__forms__buy__dates
            %p.card-date
              = "**** **** **** " + @default_card_information.last4
            %p.card-date
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year
          %p.changes
            クレジットカードを
            = link_to 'こちら', new_card_path, class:"here", data: {"turbolinks" => false}
            から変更する。
        %h3.buytitle 配達先
        - if @address.blank?
          .page__main__forms__buy__nodate
            %p 購入には配達先の登録が必要です。
            %br
              = link_to 'こちら', edit_address_path, class:"here"
              から登録する。
        - else
          .page__main__forms__buy__dates
            %p.house-date
              = @address.address_number
            %p.house-date
              = @address.prefecture
          %p.changes
            配達先を
            = link_to 'こちら', edit_address_path, class:"here", data: {"turbolinks" => false}
            から変更する。
        - if @address.blank? || @default_card_information.blank?
          %button.btnnot 購入する
        - else
          = form_tag(action: :buy, method: :post) do
            %button.btn 購入する


    .account-page__footer
      %nav
        %p プライバシーポリシー
        %p メルカリ利用規約
        %p 特定商取引に関する表記
      .account-page__footer__logo
        = link_to image_tag('logo/logo-white.png', class:"footer__logo"), root_path
        %p
        ©Merrcari, inc

app/views/cards/index.html.haml
= render 'toppage/header'

.main
  .main__box
    = render 'users/left-memu'

    .my-credit
      %h2.my-credit__title 支払い方法
      .my-credit__card
        %h3.page-name 登録しているクレジットカード
      .my-credit__show
        .my-credit__cards__show
          %figure
            = image_tag "cards/#{@card_src}", width: '90', height: '50', alt: @card_brand, id: "card_image"
          .my-credit__cards__number
            = "**** **** **** " + @default_card_information.last4
            %br.my-credit__date
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
      .my-credit__btn
        = form_tag(delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %input{ type: "hidden", name: "card_id", value: "" }
          %button.dide-btn 削除する

= render 'toppage/footer'

app/views/cards/new.html.haml
= render 'toppage/header'

.main
  .main__box
    = render 'users/left-memu'

    .my-credit
      %h2.my-credit__title クレジットカード情報入力
      .my-credit__cards
        = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
          .field
            %label.field-label カード番号
            %span.red 必須
            .field-input
              = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            = image_tag 'cards/visa.png', height: '15%', width: '15%', class: 'credit-icon'
            = image_tag 'cards/jcb.gif', height: '13%', width: '13%', class: 'credit-icon'
            = image_tag 'cards/mastercard.png', height: '15%', width: '15%', class: 'credit-icon'
            = image_tag 'cards/discover.png', height: '15%', width: '15%', class: 'credit-icon'
            = image_tag 'cards/american-express.png', height: '15%', width: '15%', class: 'credit-icon'
          .field
            %label.field-label 有効期限
            %span.red 必須
            .field-input
              %select#exp_month{name: "exp_month", type: "text", class:"select-box"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %span 月／
              %select#exp_year{name: "exp_year", type: "text", class:"select-box"}
                %option{value: ""} --
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
                %option{value: "2030"}30
              %span 年
          .field
            %label.field-label セキュリティコード
            %span.red 必須
            .field-input
              = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              #card_token
              = submit_tag "追加する", id: "token_submit", class: 'btn'

= render 'toppage/footer'

app/views/cards/show.html.haml
= render 'toppage/header'

.main-goods
  .main-goods__another
    .main-goods__another__messages
      %h3.thanks 購入が完了しました！
      %p.message 出品者からの発送をお待ち下さい。
      .main-goods__another__messages__nexts
        = link_to "トップページに戻る", root_path, class:"next"
        = link_to "マイページに戻る", user_path(current_user), data: {"turbolinks" => false}, class:"next"
= render 'toppage/footer'