config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions' }
  root to:'toppage#index'
  
  resources :users, only: [:show, :index] do
    collection do
      get 'sell', to: 'users#sell'
      get 'sold', to: 'users#sold'
    end
  end

  
  resources :cards, only: [:new, :show, :index, :edit] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
      post 'buy/:id', to: 'cards#buy'
    end
  end
  resources :toppage, only: :index

  resources :images, only: [:destroy]

  resources :products do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :categories, only: [:show, :index]
  
  resources :addresses, only: [:new, :create, :edit, :update] do
    collection do
      get 'mypage_new', to: 'addresses#mypage_new'
      post 'mypage_create', to: 'addresses#mypage_create'
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :user
  belongs_to :category
  has_many   :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name,        length: { maximum: 40 }, presence: true, on: :create
  validates :name,        length: { maximum: 40 }, presence: true
  validates :detail,      length: { maximum: 1000 }, presence: true, on: :create, on: :create
  validates :detail,      length: { maximum: 1000 }, presence: true, on: :create
  validates :category_id, presence: true, on: :create
  validates :category_id, presence: true
  validates :price,       presence: true, numericality: { only_integr: true,greater_than_or_equal_to: 270, less_than_or_equal_to: 9999999 }, on: :create
  validates :price,       presence: true, numericality: { only_integr: true,greater_than_or_equal_to: 270, less_than_or_equal_to: 9999999 }
  validates :condition,   presence: true, on: :create
  validates :condition,   presence: true
  validates :burden,      presence: true, on: :create
  validates :burden,      presence: true
  validates :days,        presence: true, on: :create
  validates :days,        presence: true
  validates_associated :images, presence: true
  validates :status,      presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, :except=>[:show]
  before_action :set_product, only: [:show, :destroy, :edit, :update]

  def index
  end

  def new
    @product = Product.new
    @product.images.build
    @category = Category.all.order("id ASC").limit(13)
    @address = Address.find_by(user_id: current_user.id)
  end

  def category_children
    @category_children = Category.find(params[:parent_name]).children 
  end

  def category_grandchildren
    @category_grandchildren = Category.find("#{params[:childId]}").children
  end

  def create
    @product = Product.new(product_params)
    @product.status = 1
      if params[:images].blank?
        @product.images.build
        redirect_to action: "new"
        flash[:notice] = "出品に失敗しました"
      elsif @product.save
          params[:images][:image].each do |image|
            @product.images.create(image: image, product_id: @product.id)
          end
        redirect_to root_path
      else
        @product.images.build
        redirect_to action: "new"
        flash[:notice] = "出品に失敗しました"
      end
  end

  def show
    @category = @product.category
    @images = @product.images
    @image = @images.first
    @address = Address.find_by(user_id: @product.user_id)
  end

  def destroy
    redirect_to root_path if @product.destroy && @product.user_id == current_user.id
  end

  def edit
    @grandchild_category = @product.category
    @child_category = @product.category.parent
    @root_category = @product.category.root
    redirect_to root_path if @product.user_id != current_user.id
  end

  def update
    redirect_to root_path if @product.user_id != current_user.id

    if params[:images].blank? && @product.images.blank?
      @product.images.build
      redirect_to action: "edit"
      flash[:notice] = "出品に失敗しました"
    elsif product_params[:name] == "" or product_params[:detail] == "" or product_params[:category_id] == "" or product_params[:price] == "" or product_params[:condition] == "" or product_params[:status] == "" or product_params[:burden] == "" or product_params[:days] == ""
      @product.images.build
      redirect_to action: "edit"
      flash[:notice] = "出品に失敗しました"
    elsif params[:images].blank?
      @product.update(params.require(:product).permit(:name, :detail, :category_id, :price, :condition, :status, :burden, :days).merge(user_id: current_user.id))
      redirect_to root_path
    elsif @product.update(product_params)
      params[:images][:image].each do |image|
        @product.images.create(image: image, product_id: @product.id)
      end
      redirect_to root_path
    else
      @product.images.build
      redirect_to action: "edit"
      flash[:notice] = "出品に失敗しました"
    end
  end


  private
  def product_params
    params.require(:product).permit(:name, :detail, :category_id, :price, :condition, :status, :burden, :days, images_attributes: [:image]).merge(user_id: current_user.id)
  end


  def set_product
    @product = Product.find(params[:id])
  end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.haml
%header
  = link_to image_tag('logo/logo.png', width:'180px', class:"icon-box"), root_path

%main
  .main-box
  
    - if flash[:notice]
      %p.flash
        = flash[:notice]
    = form_for @product,  html: {id: "item-dropzone"} do |f|
      .main-box__form__group
        .main-box__form__group__title-box
          %h3.main-box__form__group__title
            出品画像
            %span.main-box__form__group__title__s
              必須
        %p.main-box__form__group__text
          最大5枚までアップロードできます
          %br ドラッグアンドドロップまたはクリックしてファイルをダウンロード
        


        = f.fields_for :image do |image|
          .dropzone-container
            .ago-preview
              - @product.images.each_with_index do |image, idx|
                .ago-preview__box{id: "imagebox#{idx+1}"}
                  = image_tag image.image_url, size: "112x112"
                  = link_to '削除', image_path(image.id), method: "delete", class: "delete_btn", id: "btn#{idx+1}"
            #preview
            .dropzone-area
              = image.label :image, class: "dropzone-box", for: "upload-image" do
                .input_area 
                  = image.file_field :image, multiple: true, name: 'images[image][]', id: "upload-image", class: "upload-image", 'data-image': 0
            .whitebox
          .dropzone-container
            #preview2
            .dropzone-area2
              = image.label :image, class: "dropzone-box", for: "upload-image" do
                %p ここをクリックしてください



      .main-box__form__group
        %label.main-box__form__group__title
          出品名
          %span.main-box__form__group__title__s
            必須
        = f.text_field :name, id: "input-default", class: "main-box__form__group__name-form", placeholder: "40文字まで"
        .main-box__form__group__title-box
        %label.main-box__form__group__title
          出品の説明
          %span.main-box__form__group__title__s
            必須
        = f.text_area :detail, class: "main-box__form__group__explanation-form", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5"

      .main-box__form__group
        %p.main-box__form__group__name
          商品の詳細
        %label.main-box__form__group__title
          カテゴリー
          %span.main-box__form__group__title__s
            必須
        .main-box__form__group__select
          = f.collection_select :category_id, Category.roots, :id, :name, {selected: @root_category.id}, class: 'main-box__form__group__name-form', id: 'parent_category'
        .main-box__form__group__select
          = f.collection_select :category_id, @child_category.siblings, :id, :name, {selected: @child_category.id},class: 'main-box__form__group__name-form', id: 'product_child_category'
        .main-box__form__group__select{id: "displayNoneCategory"}
          = f.collection_select :category_id, @grandchild_category.siblings, :id, :name, {selected: @grandchild_category.id},class: 'main-box__form__group__name-form', id: 'product_grandchild_category'




        .main-box__form__group__title-box
        %label.main-box__form__group__title
          商品の状態
          %span.main-box__form__group__title__s
            必須
        .main-box__form__group__select
          = f.select :condition, ["新品、未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり", "傷や汚れあり", "全体的に状態が悪い"], {include_blank: "選択してください"}, {class: 'main-box__form__group__name-form'}

      .main-box__form__group
        %p.main-box__form__group__name
          配送料について
        %label.main-box__form__group__title
          配送料の負担
          %span.main-box__form__group__title__s
            必須
        .main-box__form__group__select
          = f.select :burden, ["送料込み(出品者負担)", "着払い(購入者負担)"], {include_blank: "選択してください"}, {class: 'main-box__form__group__name-form'}

        .main-box__form__group__title-box
        %label.main-box__form__group__title
          発送までの日数
          %span.main-box__form__group__title__s
            必須
        .main-box__form__group__select
          = f.select :days, ["1~2日で発送", "2~3日で発送", "4~7日で発送"], {include_blank: "選択してください"}, {class: 'main-box__form__group__name-form'}



      .main-box__form__group
        %p.main-box__form__group__name
          価格（¥300〜9,999,999
        .main-box__form__group__price-box
          %label.main-box__form__group__price-box__title-price
            販売価格
            %span.main-box__form__group__title__s
              必須
          .main-box__form__group__price-box__select
            %span.main-box__form__group__price-box__select__mark
              ¥
            = f.number_field :price, id: "price_calc", class: "main-box__form__group__price-box__select__number",placeholder: "例) 300", type: "number", min:300, max:999999, style:"text-align: right"
        .main-box__form__group__data-box
          .main-box__form__group__data-box__commission
            販売手数料（10%)
            .right_bar
            
        .main-box__form__group__data-box
          .main-box__form__group__data-box__commission
            販売利益
            %input{style: "display: none", id: "price"}
            .right_bar_2



      .main-box__form__group
        .main-box__form__group__submit-box
          = f.submit "編集する", class:"main-box__form__group__submit-box__button",id:"product_botton"
          
          = link_to "/", class:"main-box__form__group__submit-box__return" do
            .main-box__form__group__submit-box__return__text
              もどる
        %p.main-box__form__group__attention
          禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。




.footer-product
  %nav
    %p プライバシーポリシー
    %p フリマ利用規約
    %p 特定商取引に関する表記
  .footer__logo-box
    = link_to image_tag('logo/logo-white.png', class:"footer__logo")
    %p
    ©Frima, inc

app/views/products/new.html.haml
%header
  = link_to image_tag('logo/logo.png', width:'180px', class:"icon-box"), root_path



%main
  .main-box
  
    - if flash[:notice]
      %p.flash
        = flash[:notice]
    = form_for @product,  html: {id: "item-dropzone"} do |f|
      .main-box__form__group
        .main-box__form__group__title-box
          %h3.main-box__form__group__title
            出品画像
            %span.main-box__form__group__title__s
              必須
        %p.main-box__form__group__text
          最大5枚までアップロードできます
          %br
          画像は新しく追加した順に表示されます
          %br
          ドラッグアンドドロップまたはクリックしてファイルをダウンロード


        = f.fields_for :image do |image|
          .dropzone-container
            #preview
            .dropzone-area
              = image.label :image, class: "dropzone-box", for: "upload-image" do
                .input_area 
                  = image.file_field :image, multiple: true, name: 'images[image][]', id: "upload-image", class: "upload-image", 'data-image': 0


      .main-box__form__group
        %label.main-box__form__group__title
          出品名
          %span.main-box__form__group__title__s
            必須
        = f.text_field :name, id: "input-default", class: "main-box__form__group__name-form", placeholder: "40文字まで"
        .main-box__form__group__title-box
        %label.main-box__form__group__title
          出品の説明
          %span.main-box__form__group__title__s
            必須
        = f.text_area :detail, class: "main-box__form__group__explanation-form", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5"

      .main-box__form__group
        %p.main-box__form__group__name
          商品の詳細
        %label.main-box__form__group__title
          カテゴリー
          %span.main-box__form__group__title__s
            必須
        .main-box__form__group__select
          = f.collection_select :category_id, @category, :id, :name, {prompt: "---"}, class: "main-box__form__group__name-form", id: "category_select"
        .main-box__form__group__children

        .main-box__form__group__title-box
        %label.main-box__form__group__title
          商品の状態
          %span.main-box__form__group__title__s
            必須
        .main-box__form__group__select
          = f.select :condition, ["新品、未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり", "傷や汚れあり", "全体的に状態が悪い"], {include_blank: "選択してください"}, {class: 'main-box__form__group__name-form'}

      .main-box__form__group
        %p.main-box__form__group__name
          配送料について
        %label.main-box__form__group__title
          配送料の負担
          %span.main-box__form__group__title__s
            必須
        .main-box__form__group__select
          = f.select :burden, ["送料込み(出品者負担)", "着払い(購入者負担)"], {include_blank: "選択してください"}, {class: 'main-box__form__group__name-form'}

        .main-box__form__group__title-box
        %label.main-box__form__group__title
          発送までの日数
          %span.main-box__form__group__title__s
            必須
        .main-box__form__group__select
          = f.select :days, ["1~2日で発送", "2~3日で発送", "4~7日で発送"], {include_blank: "選択してください"}, {class: 'main-box__form__group__name-form'}



      .main-box__form__group
        %p.main-box__form__group__name
          価格（¥300〜9,999,999
        .main-box__form__group__price-box
          %label.main-box__form__group__price-box__title-price
            販売価格
            %span.main-box__form__group__title__s
              必須
          .main-box__form__group__price-box__select
            %span.main-box__form__group__price-box__select__mark
              ¥
            = f.number_field :price, id: "price_calc", class: "main-box__form__group__price-box__select__number",placeholder: "例) 300", type: "number", min:300, max:999999, style:"text-align: right"
        .main-box__form__group__data-box
          .main-box__form__group__data-box__commission
            販売手数料（10%)
            .right_bar
            
        .main-box__form__group__data-box
          .main-box__form__group__data-box__commission
            販売利益
            %input{style: "display: none", id: "price"}
            .right_bar_2



      .main-box__form__group
        .main-box__form__group__submit-box
          - if @address.blank?
            .page__main__forms__buy__nodate
              %p 出品には住所の登録が必要です。
              %br
                = link_to 'こちら', edit_address_path(current_user.id), class:"here"
                から登録する。
          - if @address.blank?
          - else
            = f.submit "出品する", class:"main-box__form__group__submit-box__button",id:"product_botton"
          
          = link_to "/", class:"main-box__form__group__submit-box__return" do
            .main-box__form__group__submit-box__return__text
              もどる
        %p.main-box__form__group__attention
          禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。




.footer-product
  %nav
    %p プライバシーポリシー
    %p フリマ利用規約
    %p 特定商取引に関する表記
  .footer__logo-box
    = link_to image_tag('logo/logo-white.png', class:"footer__logo")
    %p
    ©Frima, inc

app/views/products/show.html.haml
= render 'toppage/header'
.item

  .item__box
    .item__box__name
      = @product.name
    .item__box__main
      - if @product.images.blank?
      - else
        .item__box__main__image
          = image_tag @image.image.to_s, size: "350x350"
        .item__box__main__sub  
          - @product.images.each.with_index do |image, index|
            = image_tag image.image_url, size: "150x150", class: "image-sub"
      
    .item__box__price
      .item__box__price__include
        = @product.price
      .item__box__price__fee
        .item__box__price__fee__tax
          税込
        .item__box__price__fee__postage
          送料込み
    .item__box__method
      .item__box__method__box
        - if user_signed_in? && current_user.id == @product.user_id
          .item__box__method__box__btn 
            = link_to edit_product_path(@product), data: {"turbolinks" => false}, class:"item__box__method__box_btn"do
              編集
          .item__box__method__box__btn2
            = link_to product_path(@product),method: :delete,  class:"item__box__method__box_btn"do
              削除
        - elsif @product.status == "1"
          .item__box__method__box__btn3
            = link_to edit_card_path(id: @product.id), class:"item__box__method__box_btn"do
              購入画面に進む
        - else

    .item__box__information__table
      %table
        %tbody
          %tr
            %th 出品者
            %td 
              = @product.user.nickname
          %tr
            %th カテゴリー
            %td 
              .item-category
                = link_to ">#{@category.parent.parent.name}",  category_path(@category.parent.parent.id), class: "user-name-string"; 
              %br
              .item-category
                = link_to ">#{@category.parent.name}", category_path(@category.parent.id), class: "user-name-string"; 
              %br 
              .item-category
                = link_to ">#{@category.name}",  category_path(@category.id), class: "user-name-string"; 
                
          %tr
            %th 商品状態
            %td  
              .item-condition
                = @product.condition  
          %tr
            %th 送料負担
            %td  
              .item-burden
                = @product.burden
          %tr
            %th 配送元地域
            %td 
              .item-detail
                = @address.prefecture

          %tr
            %th 発送日数
            %td 
              .item-days
                = @product.days
    .item__box__detail
      = @product.detail

= render 'toppage/footer'